name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # jede Stunde
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
